### ISSUE TITLE
Add TCK tests for MicroProfile Concurrency

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#60]
Unless someone else knows of a better way to track this, I'm intending for this issue to be a place to document and collaborate on a list of test scenarios for the MicroProfile Concurrency TCK.

The following will be a checklist of scenarios. There are only a couple to start with, which seemed like some basic things we will need to start making progress. Sign up for a scenario to the TCK by mentioning the git pull number under which you are adding it. When the pull is merged, check the box next to it to indicate it is done,

- [x] #61 verify that the MP Concurrency impl provides a builder for ThreadContext
- [x] #68 verify ThreadContext.Builder API methods: cleared, propagated, unchanged
- [x] #103 verify ThreadContext builder is reusable
- [x] #69 verify ThreadContext API method: currentContextExecutor - runnables run with context
- [x] #62 verify ThreadContext API method: contextualCallable - callable runs with context
- [x] #62 verify ThreadContext API method: contextualConsumer - consumer runs with context
- [x] #62 verify ThreadContext API method: contextualFunction - function runs with context
- [x] #62 verify ThreadContext API method: contextualRunnable - runnable runs with context
- [x] #62 verify ThreadContext API method: contextualSupplier - supplier runs with context
- [x] #88, #108, #123 verify ThreadContext API method: withContextCapture - dependent actions run with context
- [x] #97 verify ThreadContext clears context types that are not configured under any category (per JavaDoc requirement)
- [x] #104, #112, #126 verify ThreadContext constants are defined and usable: TRANSACTION, SECURITY, CDI, ALL_REMAINING, and APPLICATION, to the extent that it is reasonable to do so when running the TCK.  Specifically, security context is left to the implementations to cover in their own testing due to the fact that it would introduce a dependency on servlets (HttpServletRequest.getUserPrincipal) or other vendor-specific technology that is not guaranteed to be available when running the TCK.
- [x] #61 verify that the MP Concurrency impl supports configuration and usage of third-party thread context provides supplied via the ServiceLoader
- [x] #114 The container creates a ThreadContext instance per unqualified ThreadContext injection point
- [x] #114 A ThreadContext instance that is injected by the container can be configured via `@ThreadContextConfig`
- [x] #114 If the `@NamedInstance` qualifier is present on a ThreadContext injection point that is annotated with `@ThreadContextConfig`, the container creates a ThreadContext instance that is qualified by the name value
- [x] #114 Application can provide producers of ThreadContext that are qualified by `@NamedInstance`
- [x] #95 MicroProfile Config override of ThreadContext that container produces for injection into a field
- [x] #95 MicroProfile Config override of ThreadContext that container produces for injection into a parameter
- [x] #117 verify that when you supply an already-contextualized action/task to a ManagedExecutor's runAsync or supplyAsync method, the action/task runs with the context that was originally captured for it by the ThreadContext contextualRunnable/contextualSupplier method, rather than re-capturing context per the ManagedExecutor's configuration.
- [x] #117 verify that when you supply an already-contextualized action/task to a completion stage method that creates a dependent stage (such as thenApplyAsync) the action/task runs with the context that was originally captured for it by the ThreadContext contextual* method, rather than re-capturing context per the ManagedExecutor's configuration.
- [x] #63 verify that the MP Concurrency impl provides a builder for ManagedExecutor
- [x] #70 verify ManagedExecutor.Builder API methods: cleared, propagated, maxAsync, maxQueued
- [x] #102  verify ManagedExecutor builder is reusable
- [x] #67 verify boundaries for ManagedExecutor.Builder maxAsync: positive value is enforced; -1 is allowed; negative and 0 throw an IllegalArgumentException
- [x] #67 verify boundaries for ManagedExecutor.Builder maxQueued: positive value is enforced; -1 is allowed; negative and 0 throw an IllegalArgumentException
- [x] #65 verify ManagedExecutor API method: completedFuture - dependent actions run with context
- [x] #65 verify ManagedExecutor API method: completedStage - dependent actions run with context
- [x] #65 verify ManagedExecutor API method: failedFuture - dependent actions run with context
- [x] #65 verify ManagedExecutor API method: failedStage - dependent actions run with context
- [x] #63 verify ManagedExecutor API method: newIncompleteFuture - dependent actions run with context
- [x] #63 verify ManagedExecutor API method: runAsync - action runs with context
- [x] #63 verify ManagedExecutor API method: supplyAsync - action runs with context
- [x] #84 verify ManagedExecutor API method: execute - Runnable runs with context
- [x] #84 verify ManagedExecutor API method: submit - Runnable/Callable run with context
- [x] #73 verify ManagedExecutor API method: invokeAll - Callables run with context
- [x] #73 verify ManagedExecutor API method: invokeAny - Callable(s) run with context
- [x] #71 verify ManagedExecutor API method: shutdown - additional tasks cannot be submitted
- [x] #71 verify ManagedExecutor API method: shutdownNow - additional tasks are not submitted, queued/running tasks are canceled
- [x] #100 verify ManagedExecutor clears context types that are not configured under any category (per JavaDoc requirement)
- [x] #89 The container creates a ManagedExecutor instance per unqualified ManagedExecutor injection point
- [x] #89 A ManagedExecutor instance that is injected by the container can be configured via `@ManagedExecutorConfig`
- [x] #89 If the `@NamedInstance` qualifier is present on a ManagedExecutor injection point that is annotated with `@ManagedExecutorConfig`, the container creates a ManagedExecutor instance that is qualified by the name value
- [x] #89 Application can provide producers of ManagedExecutor that are qualified by `@NamedInstance`
- [x] #89 Application can shut down a ManagedExecutor instance that is created and injected by the container
- [x] #93 MicroProfile Config override of ManagedExecutor that container produces for injection into a field
- [x] #94 MicroProfile Config override of ManagedExecutor that container produces for injection into a parameter
- [x] #105 obtain ConcurrencyManager builder, if supported by the concurrency provider, and build & register a custom instance for a class loader. Obtain the instance via getConcurrencyManager(classloader), then release it.
- [x] #126 CDI context propagation for ManagedExecutors
- [x] #126 CDI context propagation for ThreadContext
- [x] #130 Tests for transaction propagation to dependent stages

As discussed on the prior MicroProfile Concurrency call (2019-2-21), the above represents the full set of desired TCK scenarios sufficient for the initial release candidate.

**Comment by aguibert** [comment]
Here is a shared doc we can use for coordinating TCK scenarios:

(link obfuscated a bit to try and avoid any spam bots)
docs DOT google DOT 
 com/document/d/1XMzygVHvxZBtA5SlJlv7rUzo507phbYj4zUetplqTXs/edit?usp=sharing

**Comment by nmittles** [comment]
Suggestions for basic TCK scenarios of ManagedExecutor, ThreadContext and their builders:

- verify ManagedExecutor.Builder().maxAsync(X).build() boundaries; 1, -1, and maxInt is successful for X; 0 and -2 throw an IllegalArgumentException for X
- verify ManagedExecutor.Builder().maxQueued(X).build() boundaries; 1, -1, and maxInt is successful for X; 0 and -2 throw an IllegalArgumentException for X
- verify ManagedExecutor.Builder() API methods: build(), propagated(), cleared(), maxAsync(), maxQueued()
- verify ManagedExecutor API methods: builder(), completedFuture(), completedStage(), failedFuture(), failedStage(), newIncompleteFuture(), runAsync(), supplyAsync()
- verify ThreadContext.Builder() API methods: build(), cleared(), propagated(), unchanged()
- verify ThreadContext API methods: currentContextExecutor(), contextualCallable(), contextualConsumer(), contextualFunction(), contextualRunnable(), contextualSupplier(), and withContextCapture()
- verify ThreadContext constants are defined: TRANSACTION, SECURITY, CDI, ALL_REMAINING, and APPLICATION
